spring.application.name=demo
spring.data.mongodb.uri=mongodb://localhost:27017/hadasim_projec
project.hadasim.jwtSecret=MySecretKeyForHadasimProject2026!KeepItSafe?
project.hadasim.jwtExpirationMs=1800000